# Generated by Django 5.1.7 on 2025-03-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routecomment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='routes.route'),
        ),
        migrations.AddField(
            model_name='routecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeleg',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='routes.route'),
        ),
        migrations.AddField(
            model_name='routewaypoint',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_waypoints', to='places.place'),
        ),
        migrations.AddField(
            model_name='routewaypoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='routes.route'),
        ),
        migrations.AddField(
            model_name='routeleg',
            name='end_waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs_as_end', to='routes.routewaypoint'),
        ),
        migrations.AddField(
            model_name='routeleg',
            name='start_waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs_as_start', to='routes.routewaypoint'),
        ),
        migrations.AlterUniqueTogether(
            name='routewaypoint',
            unique_together={('route', 'order')},
        ),
    ]
